Add SO for holding information about enemies
BoundfoxStudios/community-project pull request #191
Opened 2023-01-19 16:30 UTC by M4lph

**Beschreibung**
SO für Informationen zu Gegnern erstellt.
closes #180 

## Checkliste

- [x] Aufgabe verlinkt (falls nicht, PR editieren)
- [ ] Tests geschrieben (nur relevant für Code-Änderungen)
- [ ] Dokumentation aktualisiert (nur relevant für System-Entwicklungen)

## PR Typ

- [ ] Bugfix
- [ ] Feature
- [ ] 3D-Modell
- [ ] 2D-Arbeit
- [ ] Sound-Effekte
- [ ] Musik
- [ ] Dokumentation
- [ ] Sonstiges, bitte beschreiben:

2023-01-20 14:58 UTC, ManuelRauber requested changes
Im Ordner `_Game/ScriptableObjects` liegt eine Datei `Enemies.meta`. 
Ich nehme an, du hast bei Dir einen leeren Ordner angelegt und keine Datei reingelegt (gibt ja noch keine Gegner). Leider kann man in Git keine leeren Ordner commiten. 

Entweder man müsste jetzt irgendeine Datei reinlegen oder wir lassen den Ordner generell weg.

Wäre für letzteres, dann müsstest Du nur grad die Enemies.meta dort wieder löschen.

(Bitte nicht verwechslen mit der Enemies.meta im Scripts/Runtime-Ordner, _die_ ist dort korrekt)

2023-01-20 14:58 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Enemies/ScriptableObjects/EnemySO.cs
> +		public LocalizedString Name { get; private set; }
Du Fuchs. Hab ich letztens auch überlegt, es mal genau so zu machen. 
Jetzt muss ich erstmal meinen Code ändern, weil das so eigentlich ziemlich angenehm ist. 😬

2023-01-20 14:58 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Enemies/ScriptableObjects/EnemySO.cs
> +		[field: SerializeField, Min(1)]
Ich würd gerne, auch wenn's sehr verbose ist in der Schreibeweise, pro Attribut eine eigene Zeile machen. So ein kleines wie `Min(0)` geht schnell mal runter.

```suggestion
		[field: SerializeField]
		[field: Min(1)]
```

Entsprechend dann bei den anderen bitte auch :)

2023-01-20 17:00 UTC, M4lph commented on CommunityProject/Assets/_Game/Scripts/Runtime/Enemies/ScriptableObjects/EnemySO.cs
> +		public LocalizedString Name { get; private set; }
Ich war mir eigentlich auch sehr sicher das ich diese Schreibweise auch schon länger von dir kenne :)

2023-01-20 20:14 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Enemies/ScriptableObjects/EnemySO.cs
> +		public LocalizedString Name { get; private set; }
Bin nur noch nicht konsequent in der Nutzung 😅

2023-01-21 16:11 UTC, ManuelRauber requested changes
🙈

2023-01-21 16:11 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Enemies/ScriptableObjects/EnemySO.cs
> +				Min(1)]
```suggestion
		[field: SerializeField]
		[field: Min(1)]
```

2023-01-21 16:11 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Enemies/ScriptableObjects/EnemySO.cs
> +				Min(0)]
```suggestion
		[field: SerializeField]
		[Min(0)]
```

2023-01-21 16:11 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Enemies/ScriptableObjects/EnemySO.cs
> +				Min(0)]
```suggestion
		[field: SerializeField]
		[field:	Min(0)]
```

2023-01-21 16:11 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Enemies/ScriptableObjects/EnemySO.cs
> +				Tooltip("Size of this enemy in meter.")]
```suggestion
		[field: SerializeField]
		[Min(0)]
		[Tooltip("Size of this enemy in meter.")]
```

2023-01-21 16:11 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Enemies/ScriptableObjects/EnemySO.cs
> +				Tooltip("The amount of experience awarded to player on kill.")]
```suggestion
		[field: SerializeField]
		[Min(0)]
		[Tooltip("The amount of experience awarded to player on kill.")]
```

2023-01-21 16:11 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Enemies/ScriptableObjects/EnemySO.cs
> +				Tooltip("The amount of currency awarded to player on kill.")]
```suggestion
		[field: SerializeField]
		[Min(0)]
		[Tooltip("The amount of currency awarded to player on kill.")]
```

2023-01-24 16:18 UTC, merged