feat: nullable
BoundfoxStudios/community-project pull request #212
Opened 2023-01-30 12:07 UTC by ManuelRauber

**Beschreibung**

@M4lph Ich hab hier jetzt mal Nullable für alles eingeschalten.
Mein Gefühl sagt mir, dass es einige Stellen vom Code verbessert, weil man jetzt eben genau weiß, ob was Null sein kann oder nicht.
_Aber_: da Unity mit dem Serialisierungszeugs arbeitet, habe ich viele Felder mit `= default!` versehen. Sonst müsste man alle Felder als `nullable` deklarieren und dann im Code ständig prüfen, ob etwas Null ist oder nicht. Den Part fand ich nicht cool, daher `= default!` und falls es dann doch null wäre, knallt es im Code sowieso. 
Man kann leider nicht den Konstruktor verwenden, sonst könnte man ggf. noch ein anderes Pattern finden. Da wir in den Event-Methoden sind (OnValidate, Awake, ...) bleibt da leider nicht ganz so viel übrig. 
Ich denke, dass das das notwendige Übel ist, um mit Nullable zu arbeiten.

Aktuell fehlt noch die Doku zu dieser Änderung, aber Du kannst gerne schon mal über den Code schauen. 

## Checkliste

- [ ] Aufgabe verlinkt (falls nicht, PR editieren)
- [ ] Tests geschrieben (nur relevant für Code-Änderungen)
- [ ] Dokumentation aktualisiert (nur relevant für System-Entwicklungen)

## PR Typ

- [ ] Bugfix
- [ ] Feature
- [ ] 3D-Modell
- [ ] 2D-Arbeit
- [ ] Sound-Effekte
- [ ] Musik
- [ ] Dokumentation
- [ ] Sonstiges, bitte beschreiben:

2023-01-31 16:42 UTC, ManuelRauber commented
@M4lph Ok, ich bin etwas frech... Ich hab den PR gehijacked um ein kleines Cleanup zu machen: 

Alle [SerializedField] (bis auf ein Script, was nur ein Testscript ist) sind jetzt Properties.

Ich hab ein `Guard.AgainstNull` eingefügt, um eine Null-Meldung rauswerfen, was für Unity-Serialisierte Felder nett sein kann, da man diese ja als "Nicht Null" deklariert und es dann im Zweifel zur Laufzeit knallt. Da bin ich mir am Ende auch nicht sicher, ob das wirklich super viel hilft, weil's ja sowieso knallt. 

Ich hatte diese Guards zuerst im OnValidate drin, das ist aber reines Chaos, da man ständig irgendwelche Nachrichten erhält, das irgendwo eine Referenz nicht drin ist. Beispielsweise hat das Katapult ein Feld für den Tower. Wenn man das Prefab vom Katapult anschaut, hat man keinen Tower, ergo würde eine Meldung kommen, dass das Feld nicht zugewiesen ist. Das ist aber super nervig, da man es dort eben nicht füllen kann und somit ein false-postive ist. Das führt dazu, dass man irgendwann die Errors ignoriert, da sie eh ständig da sind. Man kann zwar rausfinden, ob man im Prefab-Modus ist und ob das Prefab, was man anschaut, man selbst ist und entsprechend den Fehler unterdrücken oder nicht, aber: Wenn Du z.B. um das Katapult ein weiteres Prefab wrappen würdest, das immer noch kein Tower ist, dann würdest Du wieder eine Meldung bekommen, dass der Tower fehlt. Das ist alles irgendwie suboptimal. 

Ich hab die Checks daher alle nach Awake verschoben, sodass man zumindest beim Starten direkt eine Meldung bekommt. Hier stellt sich dann wieder Frage, ob sich das dann überhaupt lohnt, da es im Zweifel ja sowieso bei der Nutzung kurz drauf knallt, man bekommt ggf. einfach nur ein bisschen früher bescheid. 
Auf der anderen Seite könnte es für ScriptableObjects nett sein, um zu merken, ob was fehlt.

Alternative, hatte ich auch ausprobiert ist, dem Feld selbst ein Attribut zu geben `[field: Required]` und dann über einen custom property drawer ein Warn-Zeichen vor dem Feld hinzumalen. Dann ist es nicht störend unten im Log und man sieht, das was fehlt. 
aber: dann bekommst Du zur Laufzeit wieder erst den Error, wenn's eben an die Codestelle kommt.

kA, bin mir selbst noch unschlüssig, finde die Awake-Variante aktuell "ok", vielleicht fällt Dir ja dazu noch was ein.

2023-02-01 19:12 UTC, M4lph commented on CommunityProject/Assets/_Game/Scripts/Runtime/BuildSystem/BuildController.cs
> +			if (_buildContext is null or { IsValidPosition: false })
Doppelter Null Check.
```suggestion
			if (_buildContext is null or _buildContext.IsValidPosition: false)
```

2023-02-01 19:12 UTC, M4lph commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/BackgroundMusicPlayer.cs
> +			_audioSource = GetComponent<AudioSource>();
```suggestion
			_audioSource = gameObject.GetComponentSafe<AudioSource>();
```

2023-02-01 19:29 UTC, merged

2023-02-01 20:52 UTC, M4lph requested changes

2023-02-01 20:52 UTC, M4lph commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/Utility/AutoScroll.cs
> +			Debug.Assert(_scrollRect is not null, "_scrollRect is not null");
```suggestion
			Debug.Assert(_scrollRect is not null, "_scrollRect is null.");
```