feat: add range bonus depending on weapon y-position
BoundfoxStudios/community-project pull request #217
Opened 2023-02-03 15:51 UTC by M4lph

**Beschreibung**
Erster Entwurf um ballistischen Waffen einen Reichweitenbonus zu geben - abhängig von der Platzierung auf der Y-Achse.

Dabei wird aktuell davon ausgegangen dass tiefstes Tile nicht unter 0 ist.

closes #195 

## Checkliste

- [x] Aufgabe verlinkt (falls nicht, PR editieren)
- [ ] Tests geschrieben (nur relevant für Code-Änderungen)
- [ ] Dokumentation aktualisiert (nur relevant für System-Entwicklungen)

## PR Typ

- [ ] Bugfix
- [x] Feature
- [ ] 3D-Modell
- [ ] 2D-Arbeit
- [ ] Sound-Effekte
- [ ] Musik
- [ ] Dokumentation
- [ ] Sonstiges, bitte beschreiben:

2023-02-05 11:21 UTC, ManuelRauber commented
Hi @M4lph!

Ich denke, hier müssen wir noch etwas mehr Gehirnschmalz reinstecken :)

* PlayMode und EditMode sollten gleich sein in der Anzeige
* Eventuell sollten wir die Höhendifferenz vom Tower und nicht von der Waffe nehmen. Je höher der Tower ist, umso höher schießt die Waffe per Standard. Eventuell sollten wir es so definieren, dass der Tower per Standard auf y = 0 gebaut. Der Pivot vom Tower ist sowieso unten, d.h. wenn der Tower dann erhöht gebaut wird, haben wir die Differenz zum Nullpunkt als zusätzliche Höhe
* Was mir nicht gefällt ist, dass `Weapon` auch noch eine eigene `Range` bekommt und wir dann in die weiteren Methoden diese Range reingeben und die Waffen-Definition die ihrerseits auch wieder eine Range hat. Passt man nicht auf, hat man schnell was verwechselt.

Ich würde sogar, angesichts der Tatsache, dass später noch andere Dinge Einfluss auf die Range haben (evtl. Upgrades, Forschung) das ganze sogar etwas weiter aufbohren.

Als Gedankenspiel hab ich gerade eine eigene Klasse `EffectiveWeaponCalculator` oder sowas im Kopf. Die bekommt eine Methode, z.B.

```cs
public EffectiveWeaponDefinition Calculate(Vector3 towerPosition, WeaponDefinition weaponDefinition, Research research, ...);
```

Quasi alles, was benötigt werden würde, um die tatsächliche Waffendefinition auszurechnen, also z.B. Feuerkraft, Reichweite etc. Jeder weitere Code würde dann mit dieser EffectiveWeaponDefinition arbeiten und muss sich dort nicht mehr um irgendwelche Faktoren kümmern.
Beim Abfeuern der Waffe müsste man diese EffectiveWeaponDefinition eventuell auch dem Projektil mitgeben, da es dann beim Einschlag potentiell weitere Dinge berechnen muss, Armor, Schadenwerte, Elementarwerte etc. 

Ob das jetzt prinzipiell die richtige Idee, weiß ich auch noch nicht. 
Wir sollten nur vermeiden, dass wir zu viel ähnliche Dinge machen und nachher wird's schwierig zu verstehen, was wo wann wie genutzt wird.

2023-02-05 11:22 UTC, ManuelRauber reviewed
Siehe Kommentar oben dran

2023-02-05 15:43 UTC, M4lph commented
>     * PlayMode und EditMode sollten gleich sein in der Anzeige
Wird umgesetzt :)
>     * Eventuell sollten wir die Höhendifferenz vom Tower und nicht von der Waffe nehmen. Je höher der Tower ist, umso höher schießt die Waffe per Standard.
Hier ging ich davon aus, dass die einzelnen Waffentypen immer auf dem selben Turm mit gleicher Höhe gebaut werden, daher dache ich, es würde keinen Unterschied machen :)
>     * Was mir nicht gefällt ist, dass `Weapon` auch noch eine eigene `Range` bekommt und wir dann in die weiteren Methoden diese Range reingeben und die Waffen-Definition die ihrerseits auch wieder eine Range hat. Passt man nicht auf, hat man schnell was verwechselt.
Gefällt mir so in der Tat auch nicht, hatte hier halt auch schon die Forschung und so weiter im Sinn, hab mich halt nicht getraut 
direkt sowas wie die EffectiveWeaponDefinition daraus zu machen :D

2023-02-18 13:05 UTC, ManuelRauber requested changes
Ein paar kleine Sachen sind mir noch aufgefallen.
Ansonsten gefällt mir das glaub ich mit den generic constraints so ganz gut, auch wenn man natürlich etwas mehr angeben muss. Dafür ist's absolut klar, was man erhält.

2023-02-18 13:05 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Entities/Weapons/BallisticWeapons/EffectiveBallisticWeaponDefinition.cs
> +		public float MaximumRange
Bei beiden Properties seh ich hier noch ein Problem:

Wenn man sie ändert, wird die Property "Range" nicht mit geändert. D.h. Du müsstest im Setter hier auch noch auf `_range` schreiben.

2023-02-18 13:05 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Entities/Weapons/BallisticWeapons/ScriptableObjects/EffectiveBallisticWeaponCalculatorSO.cs
> +		private Limits2 CalculateMaxRange(BallisticWeaponSO weaponDefinition, Vector3 weaponPosition)
```suggestion
			var range = CalculateMaximumRange(weaponDefinition, weaponPosition);
			var result = new EffectiveBallisticWeaponDefinition(range, weaponDefinition.FireRateInSeconds, weaponDefinition.AttackAngle);
			return result;
		}

		private Limits2 CalculateMaximumRange(BallisticWeaponSO weaponDefinition, Vector3 weaponPosition)
```

2023-02-18 13:05 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Entities/Weapons/Weapon.cs
> +		public TEffectiveWeaponDefinition? EffectiveWeaponDefinition { get; private set; }
```suggestion
    private TEffectiveWeaponDefinition? _effectiveWeaponDefinition;
    
		public TEffectiveWeaponDefinition EffectiveWeaponDefinition => _effectiveWeaponDefinition ??= CalculateEffectiveWeaponDefinition();
```

Hat den Vorteil, dass der Zugriff auf `EffectiveWeaponDefinition` nicht mehr null zurück geben kann, d.h. die Änderungen am `TargetLocatorSO` mit dem Hinzufügen von `?` könnte man rückgängig machen.

Plus, das müsste man mal ausprobieren, könnten die Gizmos nun auch auf `EffectiveWeaponDefinition` zugreifen anstatt auf `WeaponDefinition`, damit müsste man dann auch im Editor die echte Reichweite sehen.

2023-02-18 13:05 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Entities/Weapons/Weapon.cs
> +
Mit der zuvor vorgeschlagenen Änderung an `EffectiveWeaponDefinition` könnte diese Aufruf hier entfernt werden.

2023-02-18 21:08 UTC, M4lph commented on CommunityProject/Assets/_Game/Scripts/Runtime/Entities/Weapons/BallisticWeapons/EffectiveBallisticWeaponDefinition.cs
> +		public float MaximumRange
Uhja, die Richtung hatte ich leider nicht bedacht 👍

2023-02-19 13:44 UTC, ManuelRauber approved these changes

2023-02-19 14:53 UTC, merged