feat: add preview for tower range
BoundfoxStudios/community-project pull request #239
Opened 2023-02-23 22:56 UTC by M4lph

**Beschreibung**
Erste Implementierung für Anzeige der Reichweite der Türme.
Funktioniert mit einem Decal Projector. Der Shader auf dem Material das projiziert wird hat bietet Einstellmöglichkeiten für Dicke der Umrandung, und deren Farbe, sowie die Farbe der "Füllung".
Properties wie MinMaxRange und AttackAngle müssen dann vom Aufrufer gesetzt werden, sowie die Skalierung auf dem Decal Projector selbst.
Closes #194 

## Checkliste

- [x] Aufgabe verlinkt (falls nicht, PR editieren)
- [ ] Tests geschrieben (nur relevant für Code-Änderungen)
- [ ] Dokumentation aktualisiert (nur relevant für System-Entwicklungen)

## PR Typ

- [ ] Bugfix
- [x] Feature
- [ ] 3D-Modell
- [ ] 2D-Arbeit
- [ ] Sound-Effekte
- [ ] Musik
- [ ] Dokumentation
- [ ] Sonstiges, bitte beschreiben:

2023-02-24 08:03 UTC, ManuelRauber requested changes
Ich hab im Prefab gesehen, dass sowohl Width und Height einen Wert von `7.99` haben. Wie kommt das zustande? 
Ok, nach rumprobieren ist das ja die Box, in der gemalt wird. D.h. die müsste auch dynamisch an die MaxRange angepasst werden.

Was komisch ist: Dein MinMax Vector2 wird im Inspector als Vector4 angezeigt. Das scheint wohl ein Unity Issue zu sein 🤔 

Eine Sache wäre noch nice: Ein Script auf dem Prefab, dem man einfach eine EffectiveWeapon geben kann und es dann die Range anpasst. Möchtest Du das noch dazu machen?
In dem Fall würde ich auch sagen, dass es selbst prüfen muss, welchen konkreten Typ es hat (oder wir machen eine abstract-Methode in EffectiveWeapon rein, die die richtigen Werte für MinMax rausliefert).

2023-02-24 09:06 UTC, M4lph commented
> Ich hab im Prefab gesehen, dass sowohl Width und Height einen Wert von `7.99` haben. Wie kommt das zustande? Ok, nach rumprobieren ist das ja die Box, in der gemalt wird. D.h. die müsste auch dynamisch an die MaxRange angepasst werden.
Ja die muss ebenfalls von außen mitgegeben werden, immer etwas kleiner als die tatsächliche Range, da sonst ein Teil des Kreises über die Ecken projiziert wird.
> Was komisch ist: Dein MinMax Vector2 wird im Inspector als Vector4 angezeigt. Das scheint wohl ein Unity Issue zu sein thinking
Ja, auch wohl schon länger, siehe https://issuetracker.unity3d.com/issues/shaderegraph-vector2-and-vector3-properties-of-a-shader-are-displayed-as-vector4-properties
> Eine Sache wäre noch nice: Ein Script auf dem Prefab, dem man einfach eine EffectiveWeapon geben kann und es dann die Range anpasst. Möchtest Du das noch dazu machen? In dem Fall würde ich auch sagen, dass es selbst prüfen muss, welchen konkreten Typ es hat (oder wir machen eine abstract-Methode in EffectiveWeapon rein, die die richtigen Werte für MinMax rausliefert).
Wird erledigt :+1:

2023-02-24 11:11 UTC, ManuelRauber commented
> > Ich hab im Prefab gesehen, dass sowohl Width und Height einen Wert von `7.99` haben. Wie kommt das zustande? Ok, nach rumprobieren ist das ja die Box, in der gemalt wird. D.h. die müsste auch dynamisch an die MaxRange angepasst werden.
> 
> Ja die muss ebenfalls von außen mitgegeben werden, immer etwas kleiner als die tatsächliche Range, da sonst ein Teil des Kreises über die Ecken projiziert wird.

Ok, das können wir ja in dem Script dann verankern, das reicht ja, wenn dieses Script das weiß mit den Anpassungen.

> > Was komisch ist: Dein MinMax Vector2 wird im Inspector als Vector4 angezeigt. Das scheint wohl ein Unity Issue zu sein thinking
> 
> Ja, auch wohl schon länger, siehe https://issuetracker.unity3d.com/issues/shaderegraph-vector2-and-vector3-properties-of-a-shader-are-displayed-as-vector4-properties

Fun Fact: Im Blueprint-Material und Simple-Water, die auch beide einen eigenen Shader haben mit Vector2, da passiert's nicht 🤔 

> > Eine Sache wäre noch nice: Ein Script auf dem Prefab, dem man einfach eine EffectiveWeapon geben kann und es dann die Range anpasst. Möchtest Du das noch dazu machen? In dem Fall würde ich auch sagen, dass es selbst prüfen muss, welchen konkreten Typ es hat (oder wir machen eine abstract-Methode in EffectiveWeapon rein, die die richtigen Werte für MinMax rausliefert).
> 
> Wird erledigt 👍

Danke!

2023-02-27 11:43 UTC, ManuelRauber commented
@allcontributors please add @HAliss for design

2023-03-02 12:51 UTC, ManuelRauber approved these changes

2023-03-02 12:51 UTC, merged