feat: Graphy Implementation
BoundfoxStudios/community-project pull request #242
Opened 2023-02-24 22:53 UTC by SuperPirate-ai

**Beschreibung**
Implementierung von Graphy und Erstellung eines Scriptes, dass beim ReleaseBuild alle Objecten, die 'DevelopmentOnly' als Tag haben, löscht. Issue: #234 
## Checkliste

- [ ] Aufgabe verlinkt (falls nicht, PR editieren)
- [ ] Tests geschrieben (nur relevant für Code-Änderungen)
- [ ] Dokumentation aktualisiert (nur relevant für System-Entwicklungen)

## PR Typ

- [ ] Bugfix
- [ ] Feature
- [ ] 3D-Modell
- [ ] 2D-Arbeit
- [ ] Sound-Effekte
- [ ] Musik
- [ ] Dokumentation
- [ ] Sonstiges, bitte beschreiben:

2023-02-26 12:38 UTC, ManuelRauber requested changes
In Graphy bitte noch folgende Einstellungen im Inspektor anpassen:

- [ ] Keep alive ausschalten
- [ ] Enable Hotkeys einschalten (Standardeinstellungen für Hotkeys sind dann in Ordnung)

2023-02-26 12:38 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Editor/OnBuildDestroyObjsManager.cs
> +	public class OnBuildDestroyObjsManager : IProcessSceneWithReport
```suggestion
	public class StripDevelopmentOnlyObjectsFromBuild : IProcessSceneWithReport
```

Bitte den Dateinamen auch mit anpassen :)

2023-02-26 12:38 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Editor/OnBuildDestroyObjsManager.cs
> +		public int callbackOrder { get { return 0; } }
```suggestion
		public int callbackOrder { get; }
```

Ist per Default bereits 0

2023-02-26 12:38 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Editor/OnBuildDestroyObjsManager.cs
> +
```suggestion
      if (report is null || report.summary.options.HasFlag(BuildOptions.Development)) {
        return;
      }

			var objectsToDelete = GameObject.FindGameObjectsWithTag("DevelopmentOnly");

			for (var i = objectsToDelete.Length - 1; i >= 0; i--)
			{
			  Object.DestroyImmediate(objectsToDelete[i]);
			}
```

Hab ein paar Dinge hier drin korrigiert:

* Wir bevorzugen `var` anstelle den Typen im Community-Projekt.
* Zuerst prüfen, ob wir im Development-Modus sind und dann direkt die Methode beenden. Spart an Einrückungstiefe
* Beim Zerstören von Elementen sollte man immer rückwärts durch die Schleife laufen. Es kann durchaus mal passieren, dass Dinge ineinander verschaltelt sind, dann würde ein Eltern-Objekt auch die Kinder löschen und es kommt dann zum Fehler, da wir versuchen in der nächsten Iteration auf die Kinder zuzugreifen.

2023-02-26 21:41 UTC, M4lph requested changes
![grafik](https://user-images.githubusercontent.com/18291863/221439070-3ebf37d8-2edf-4bfa-b624-b778587126e8.png)

Habt ihr den Bug auch, das alle Zahlen wild übereinander gezeichnet werden?

2023-02-26 21:41 UTC, M4lph commented on CommunityProject/.vsconfig
> +}
Die Datei hatten wir bisher nie mit commited. Wäre eigentlich auch für VS Nutzer angenehm da was zu machen.
In der Form ist sie wohl aber wenig hilfreich. Oder eher ein Fall für .gitignore?

2023-02-26 21:41 UTC, M4lph commented on CommunityProject/Assets/_Game/Scripts/Editor/StripDevelopmentOnlyObjectsFromBuild.cs
> +using System.Collections;
```suggestion
```

2023-02-26 21:41 UTC, M4lph commented on CommunityProject/Assets/_Game/Scripts/Editor/StripDevelopmentOnlyObjectsFromBuild.cs
> +using System.Collections.Generic;
```suggestion
```

2023-02-26 21:41 UTC, M4lph commented on CommunityProject/Assets/_Game/Scripts/Editor/StripDevelopmentOnlyObjectsFromBuild.cs
> +using System.Linq;
```suggestion
```

2023-02-26 21:41 UTC, M4lph commented on CommunityProject/Assets/_Game/Scripts/Editor/StripDevelopmentOnlyObjectsFromBuild.cs
> +		public void OnProcessScene(Scene scene, BuildReport report)
```suggestion
		public void OnProcessScene(Scene scene, BuildReport? report)
```

Mit den nullable reference types wäre `report is null` immer false, deswegen markieren das wir hier auch null erwarten.

2023-02-27 18:08 UTC, ManuelRauber commented
> ![grafik](https://user-images.githubusercontent.com/18291863/221439070-3ebf37d8-2edf-4bfa-b624-b778587126e8.png)
> 
> Habt ihr den Bug auch das alle Zahlen wild übereinander gezeichnet werden?

Du darfst es nicht in der PersistentScene starten, die hat keine Camera, daher findet kein "Clearing" vom Bildschirm statt und es sieht aus, als liegt alles übereinander. Wenn Du das MainMenu startest, ist alles fein:

![image](https://user-images.githubusercontent.com/740791/221647335-ac3f7249-1057-4b41-873f-92d4373801e8.png)

2023-02-27 18:10 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Editor/StripDevelopmentOnlyObjectsFromBuild.cs
> +		public void OnProcessScene(Scene scene, BuildReport report)
@M4lph Guter Fang, hatte ich gesehen, aber nicht beachtet, weil ich dachte, dass dann das Interface nicht mehr erfüllt wird. Gerade ausprobiert und das Interface zählt weiterhin als erfüllt. Das ist gut :)

2023-02-27 18:14 UTC, ManuelRauber commented on CommunityProject/.vsconfig
> +}
Sollte für VS Nutzer sein, können wir daher mitnehmen.
VS Code Zeugs brauchen wir nicht, wird nicht mehr offiziell von Unity unterstützt: https://forum.unity.com/threads/update-on-the-visual-studio-code-package.1302621/

2023-03-02 09:47 UTC, ManuelRauber approved these changes
Danke!

2023-03-02 11:21 UTC, M4lph approved these changes
Top, danke!

2023-03-02 11:21 UTC, merged