refactor: TargetLocator
BoundfoxStudios/community-project pull request #267
Opened 2023-04-13 08:14 UTC by M4lph

**Beschreibung**
TargetType ist nun als ScriptableObject implementiert statt als Enum. Damit kann der Code zum wählen des Ziels aus nutzenden Klassen wie dem TargetLocator gezogen werden.
Resolves #200 

## Checkliste

- [x] Aufgabe verlinkt (falls nicht, PR editieren)
- [ ] Tests geschrieben (nur relevant für Code-Änderungen)
- [ ] Dokumentation aktualisiert (nur relevant für System-Entwicklungen)

## PR Typ

- [ ] Bugfix
- [ ] Feature
- [ ] 3D-Modell
- [ ] 2D-Arbeit
- [ ] Sound-Effekte
- [ ] Musik
- [ ] Dokumentation
- [ ] Sonstiges, bitte beschreiben:

2023-04-13 18:21 UTC, ManuelRauber requested changes
Eventuell die eine Auffälligkeit, sonst fein 👍

2023-04-13 18:21 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Entities/Weapons/Targeting/ScriptableObjects/RandomTargetTypeSO.cs
> +				return targets.Result.PickRandom(targets)!;
```suggestion
				return targets.Result.PickRandom(targets, targets.Size)!;
```

Oder? Sonst haben wir den #262 direkt wieder drin? :D

2023-04-13 19:30 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Entities/Weapons/Targeting/ScriptableObjects/RandomTargetTypeSO.cs
> +				return targets.Result.PickRandom(targets)!;
Sollte eigentlich so passen :)
Zum einen haben wir aktuell keine Überladung mit 2 Parametern, zum anderen hast du einen impliziten Operator vom NoAllocArrayResult zu int, der die Size zurück gibt. Der Wert wird so als int aktuell auch dem Parameter mitgegeben :)
Können aber auch explizit targets.Size meinetwegen verwenden, um das ganze vllt etwas offensichtlicher zu machen.

2023-04-15 07:53 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Entities/Weapons/Targeting/ScriptableObjects/RandomTargetTypeSO.cs
> +				return targets.Result.PickRandom(targets)!;
> Sollte eigentlich so passen :) Zum einen haben wir aktuell keine Überladung mit 2 Parametern, zum anderen hast du einen impliziten Operator vom NoAllocArrayResult zu int, der die Size zurück gibt. Der Wert wird so als int aktuell auch dem Parameter mitgegeben :) Können aber auch explizit targets.Size meinetwegen verwenden, um das ganze vllt etwas offensichtlicher zu machen.

Du hast vollkommen Recht. 
Ich hab das PickRandom auf das `targets` in der Klammer bezogen und nicht das `targets` vom `return`. :D

2023-04-15 07:53 UTC, merged