Feature/build system fix
BoundfoxStudios/community-project pull request #293
Opened 2023-04-27 18:17 UTC by ManuelRauber

**Beschreibung**

Behebt die fehlerhafte Positionierung von Towern durch den BuildController.
Wichtigste Änderung ist, dass alle Terrain-Tiles auf einem eigenen Layer liegen und ein weiteres Script haben, dass bestimmt, ob auf dem Tile gebaut werden darf oder nicht.

Vorher gab es nur "Buildable" und "Obstacle" Layer, was es unmöglich gemacht hat, herauszufinden, ob man ein ungültiges Terrain-Tile oder wirklich ein Obstacle trifft. 

Plus, bei der Berechnung/Casting hab ich einige Anpassungen gemacht, sodass wir eigentlich jede Konstellation von Tiles abfrühstücken sollten. _Eigentlich_ :-))

https://user-images.githubusercontent.com/740791/234955515-58e444a5-1b14-4465-ac68-3773e4c80a37.mov

fixes #290  

## Checkliste

- [ ] Aufgabe verlinkt (falls nicht, PR editieren)
- [ ] Tests geschrieben (nur relevant für Code-Änderungen)
- [ ] Dokumentation aktualisiert (nur relevant für System-Entwicklungen)

## PR Typ

- [x] Bugfix
- [ ] Feature
- [ ] 3D-Modell
- [ ] 2D-Arbeit
- [ ] Sound-Effekte
- [ ] Musik
- [ ] Dokumentation
- [ ] Sonstiges, bitte beschreiben:

2023-04-30 17:41 UTC, M4lph requested changes

2023-04-30 17:41 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scenes/Managers/Gameplay.unity
> +  <LevelContainerRuntimeAnchor>k__BackingField: {fileID: 0}
Warum ist das überbleibsel noch hier? Im Editor sehe ich nichts mehr davon und der Typ der dort referenziert wurde, existiert nicht mehr...

2023-04-30 17:41 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/BuildSystem/BuildController.cs
> +			var needsMaterialSwap = _buildContext.PreviousHasValidPosition != hasValidPosition;
Hier wird nicht der Fall abgefangen, bei dem du mit einem ungültigen Tile startest - Nach drücken des Build Buttons kannst du die Maus über ein ungültiges Tile bewegen, bekommst aber das gültige Material vom Tower angezeigt, nur ohne Reichweite.

2023-04-30 17:41 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/BuildSystem/BuildController.cs
Wenn man einen Tower platzieren will, dabei mit der Maus über eine Wand fährt, wird je nachdem aus welcher Richtung man das tut, der Tower auf der erhöhten Stelle platziert, oder auf dem Tile nebenan.
Fühlt sich meiner Meinung nach etwas inkonsistent an. Nicht tragisch im großen und ganzen, aber fiel mir vom Verhalten her auch auf :)
Meine Erwartung war wohl auch, dass egal aus welcher Richtung man über eine Wand fährt, der Turm auf die erhöhte Stelle kommen würde.
Leider nimmt meine Bildschirmaufnahme keinen Mauszeiger mit auf, sonst hätte ich ein Video mit anhängen können, wäre vllt etwas besser zu sehen was ich meine...

2023-04-30 17:41 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/BuildSystem/BuildController.cs
> +				out var terrainBoxWithObstaclesHit, Quaternion.identity, 20, _terrainAndObstacleLayerMask);
Vllt terrainWithObastacleBoxHit? Und für die magischen 20 auch eine eigene Variable?

2023-05-01 08:01 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/BuildSystem/BuildController.cs
Das stimmt leider, ich weiß welches Problem Du hier ansprichst. Das obliegt leider einfach der mathematischen Rundung, ob wir auf ein Feld platzieren oder auf den Nachbarn. 

Ich hab an dem Stück vom Code länger rumgewurstelt, damit es wenigstens so funktioniert wie jetzt (sonst hat's das teilweise sehr komisch gestellt oder auf dem Nachbarn auf Y-Achse nur verschoben). 

Wenn wir das verbessern wollen, müssten wir eventuell rausfinden, aus welcher Richtung wir kommen, um dann zu entscheiden, ob wir den `threshold` addieren oder subtrahieren müssen.

Ich mach hieraus mal ein Ticket und dann können wir uns das bei Gelegenheit anschauen.

2023-05-01 08:24 UTC, M4lph approved these changes

2023-05-01 08:24 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/BuildSystem/BuildController.cs
> +			var needsMaterialSwap = _buildContext.PreviousHasValidPosition is null
Hier war mein erster Gedanke einfach das invalid Material als "default" Material auf dem Blueprint zu setzen - so könnte man sich die (in den meisten Fällen) unnötigen Null-Checks sparen und müsste den bool nicht als nullable markieren.
Wäre eventuell nicht so schön im Editor, aber sollte glaube ich auch funktionieren, weitere Nachteile würden mir gerade nicht einfallen.

2023-05-01 09:01 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/BuildSystem/BuildController.cs
> +			var needsMaterialSwap = _buildContext.PreviousHasValidPosition is null
> Hier war mein erster Gedanke einfach das invalid Material als "default" Material auf dem Blueprint zu setzen - so könnte man sich die (in den meisten Fällen) unnötigen Null-Checks sparen und müsste den bool nicht als nullable markieren. Wäre eventuell nicht so schön im Editor, aber sollte glaube ich auch funktionieren, weitere Nachteile würden mir gerade nicht einfallen.

Jain, ich plädiere hier auf Datenkonsistenz. Initial wissen wir nicht, ob die Position valide ist oder nicht. Durch das Nullable erklären wir genau das: Wir wissen es nicht und finden es erst noch raus. :)

2023-05-01 10:09 UTC, merged