added view build number in scene main menu
BoundfoxStudios/community-project pull request #41
Opened 2022-09-22 18:15 UTC by ThKattanek

**Beschreibung**
Die Build Nummer wird jetzt im Main Menü angezeigt.
https://github.com/BoundfoxStudios/community-project/issues/40

## Checkliste

- [ ] Aufgabe verlinkt (falls nicht, PR editieren)
- [ ] Tests geschrieben (nur relevant für Code-Änderungen)
- [ ] Dokumentation aktualisiert (nur relevant für System-Entwicklungen)

## PR Typ

- [ ] Bugfix
- [ ] Feature
- [ ] 3D-Modell
- [ ] 2D-Arbeit
- [ ] Sound-Effekte
- [ ] Musik
- [ ] Dokumentation
- [ ] Sonstiges, bitte beschreiben:

2022-09-22 18:16 UTC, ThKattanek commented
Ich bin mir etwas unsicher ob das mit den UniTask so richtig gelöst ist. Bin noch am üben :)

2022-09-23 11:53 UTC, ManuelRauber requested changes
Siehe Kommentare im Review. 

Dazu noch ein paar Hinweise: 

* In der Scene ist ein neuer Canvas drin. Den bitte entfernen und das Prefab "Canvas" nutzen, da dies bereits korrekt eingestellt ist.
* Benamung vom GameObject für die BuildInfo passt nicht, hier wäre `BuildNumberText` schöner.
* Der Standardtext vom TMP ist "New Text", da könnte man auch hier bereits einfach ein `Build: 123 (shortsha)` reinschreiben, sodass man weiß, womit dieser Text später gefüllt sein wird.
* Und final meckert der Linter noch, da Du Spaces statt Tabs genutzt hast, um den Code zu formatieren.

_Eigentlich_ sollte Dein Programm, mit dem Du den Code bearbeitest, sich automatisch aufgrund der .editorconfig einstellen. Eventuell musst du hier mal schauen, ob Du da noch was aktivieren musst, je nach dem, welche IDE/Tool Du nutzt. :)

2022-09-23 11:53 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +namespace BoundfoxStudios.CommunityProject
```suggestion
namespace BoundfoxStudios.CommunityProject.UI
```

Siehe https://github.com/BoundfoxStudios/community-project/blob/develop/docs/contributing/technical/coding-conventions.md#programmierung "Nutze Namespaces"

2022-09-23 11:53 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +    public class ViewBuildNumber : MonoBehaviour
```suggestion
    [AddComponentMenu(Constants.MenuNames.UI + "/" + nameof(ViewBuildNumber))]
    public class ViewBuildNumber : MonoBehaviour
```

Siehe z.B. LoadingScreen als Beispiel.

Für @ManuelRauber: Muss noch in die Dokumentation rein.

2022-09-23 11:53 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +        private BuildManifestReader bmReader = new BuildManifestReader();
Bitte keine Abkürzungen benutzen, siehe https://github.com/BoundfoxStudios/community-project/blob/develop/docs/contributing/technical/coding-conventions.md#bezeichner

2022-09-23 11:53 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +        void Start()
`Awake` statt `Start`.

Ich hab's bisher immer so gehandhabt, dass Awake die internen Dinge der Klasse aktualisiert und Start die externen Dinge. Müssen wir mal schauen, ob's hier auch Sinn macht. :)

Für @ManuelRauber Fehlt noch in der Doku.

2022-09-23 11:53 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +                BuildNumberText.text = string.Format("Build: {0} ({1})", Application.version, unibm.ShortSha);
```suggestion
                BuildNumberText.text = $"Build: {Application.version} ({unibm.ShortSha})";
```

String-Interpolation statt string.Format.

2022-09-23 11:53 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +            BuildNumberText = this.gameObject.GetComponent<TextMeshProUGUI>();
Bitte kein `this` benutzen, ist fast immer unnötig in C#. :) 
Du kannst hier direkt `GetComponent<...>` schreiben.

In der Regel bin ich auch kein Freund von `GetComponent`, wenn man die Dinge auch über ein serialisiertes Feld bekommen könnte, um das Skript flexibler zu machen, wo man es ablegt. 

Wenn wir hier GetComponent nutzen, dann sollte auf die Klasse auch ein `[RequireComponent(typeof(TextMeshProUGUI))]` sodass man es nie vergessen kann. 

Für @ManuelRauber: Fehlt noch in der Dokumentation.

2022-09-23 11:53 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +            LoadBuildManifestAsyncAction.Invoke();
Hier nutzen wir eigentlich einen ziemlichen Seiteneffekt aus, dass die Methode `InitLoadBuildManifestAsyncAction()` ein internes Feld setzt, dass wir dann hinterher aufrufen.
Das ist eher Uncool und könnte die Methode an sich direkt machen.

2022-09-23 11:53 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +        private TextMeshProUGUI BuildNumberText;
```suggestion
        private TextMeshProUGUI _buildNumberText;
```

Das kann leider der Linter noch nicht automatisch prüfen, da bin ich noch am Werkeln, wie das. geht. Bzgl. der Benamung siehe auch: https://github.com/BoundfoxStudios/community-project/blob/develop/docs/contributing/technical/coding-conventions.md#groß-kleinschreibung

2022-09-23 11:53 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +        public BuildManifest unibm;
Bitte keine Abkürzung benutzen.

Gibt's einen Grund, warum das öffentlich ist?

2022-09-24 04:17 UTC, ThKattanek commented
Ups, da habe ich ja noch einiges zu Ändern. Werde ich alles im laufe des Tages durchgehen und fixen.

2022-09-24 05:04 UTC, ManuelRauber commented
> Ups, da habe ich ja noch einiges zu Ändern. Werde ich alles im laufe des Tages durchgehen und fixen. 

Oh, eine Sache fällt mir noch ein: schau mal in den InitializationLoader, wie ich dort die Start implementiert hab. Das kannst du hier auch machen, um direkt in den async/await-Kontext zu kommen. :)

2022-09-24 10:04 UTC, ThKattanek commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +        public BuildManifest unibm;
Kein Grund, stelle ich auf Private :)

2022-09-24 11:38 UTC, ThKattanek commented
So, den Rest mache ich morgen muss jetzt los :)

2022-09-25 07:05 UTC, ManuelRauber commented
> So, den Rest mache ich morgen muss jetzt los :)

Oh, eine Sache die generell noch aus dem Ticket fehlt: Beim Klick auf die Build-Nummer soll diese in die Zwischenablage kopiert werden :)

2022-09-25 11:40 UTC, ThKattanek commented
> > So, den Rest mache ich morgen muss jetzt los :)
> 
> Oh, eine Sache die generell noch aus dem Ticket fehlt: Beim Klick auf die Build-Nummer soll diese in die Zwischenablage kopiert werden :)

Erledigt.

2022-09-25 13:20 UTC, ThKattanek commented
So, ich bin durch. Wieder einiges dazu gelernt. Schau mal rüber ob das jetzt so alles passt.

2022-09-25 14:25 UTC, ManuelRauber requested changes
Fast ham was. :)

Eigentlich ist nur eine größere Kleinigkeit drin, da die MEthode `CreateBuildNumber` nicht genutzt wird. :) 

Die restlichen Sachen sind Anmerkungen auf hohen Niveau. 👍

2022-09-25 14:25 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +
Leerzeile entfernen :)

2022-09-25 14:25 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +		private async UniTask CreateBuildNumber()
Generell, das kommt von den .NET Coding Guidelines, werden Async-Methoden auch immer als solche bezeichnet. D.h. im Idealfall heißt die Methode `CreateBuildNumberAsync`

2022-09-25 14:25 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +		private BuildManifestReader _buildManifestReader = new BuildManifestReader();
Die Erzeugung würde ich auch in `CreateBuildNumber` reinlegen, damit der Speicher direkt aufgeräumt werden kann. Brauchen wir ja nur einmalig zum Laden. Sonst hält das Skript hier die ganze Zeit die Instanz, bis man das Menü verlässt.

An sich absolut nicht tragisch, ich bin nur Freund davon, Dinge so lokal zu halten, wie möglich. :)

2022-09-25 14:25 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +		private async UniTask CreateBuildNumber()
Und Frage: Jetzt haben wir zwar eine Methode, aber sie wird nicht genutzt? :)

Vorschlag: Die Methode `CreateBuildNumberAsync()` macht folgendes:

1. Erstellt eine Instanz vom `BuildManifestReader`
2. Lädt das Manifest
3. Gibt den erstellten String zurück.

In `Awake` wird die Methode `CreateBuildNumberAsync()` aufgerufen und ihr Ergebnis auf `_buildNumberText.text` geschrieben.

2022-09-25 14:25 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +		// Kopiert die Buildnummer in die Windows Zwischenablage
Kommentar ist redundant und kann entfernt werden, Methodenname ist bereits aussagekräftig genug.

2022-09-25 14:31 UTC, ThKattanek commented
> Eigentlich ist nur eine größere Kleinigkeit drin, da die MEthode `CreateBuildNumber` nicht genutzt wird. :)

Ich wollt's entfernen und am Ende doch vergessen. :)

2022-09-25 14:33 UTC, ManuelRauber commented
> > Eigentlich ist nur eine größere Kleinigkeit drin, da die MEthode `CreateBuildNumber` nicht genutzt wird. :)
> 
> Ich wollt's entfernen und am Ende doch vergessen. :)

Dafür gibt's ja dann den Review :)

2022-09-25 15:22 UTC, ThKattanek commented
Fertig :)

2022-09-25 15:24 UTC, ManuelRauber requested changes
Ein letztes noch, dann haben wir's :)

2022-09-25 15:24 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +			BuildManifestReader _buildManifestReader = new BuildManifestReader();
`var` :)

2022-09-25 15:33 UTC, ThKattanek commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/ViewBuildNumber.cs
> +			BuildManifestReader _buildManifestReader = new BuildManifestReader();
Erledigt! Evtl. jetzt fertig? ;)

2022-09-25 15:34 UTC, ManuelRauber approved these changes
Herzlichen Dank! :)

2022-09-25 16:28 UTC, merged

2022-10-18 07:52 UTC, ManuelRauber commented
@all-contributors please add @ThKattanek for code