Bug: Einstellungen werden nicht korrekt gespeichert.
BoundfoxStudios/community-project pull request #425
Opened 2024-01-01 13:41 UTC by M4lph

- Standardeinstellungen werden jetzt vom SettingSO selbt übernommen (Aus SettingController verschoben, da auf das SO schon während Init Szene zugegriffen werden kann.)
- SettingSO LoadAsync gibt bool zurück als Erfolgsindikator.
- Falls bei Start des Spiels keine .config Datei vorhanden ist, wird eine erstellt.

Bisher wurden immer die Werte erstmal gespeichert, die bei aufrufen des parameterlosen Konstruktors der GameSettings Klasse erzeugt wurden. Auch die "mutableSettings" die im UI benutzt wurden, haben wohl erstmal mit einem völlig neuem Objekt gearbeitet.

Fixes #420

2024-01-08 13:47 UTC, ManuelRauber requested changes

2024-01-08 13:47 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Infrastructure/SceneManagement/InitializationLoader.cs
> +			}
Ich würd vorschlagen, dass direkt in den Settings zu handeln. 

Wenn `LoadAsync` nichts findet, dann soll es die Standardwerte setzen. So hat's das bisher auch gemacht (implizit, durch die Zuweisungen der einzelnen Settings in den jeweiligen Kategorie-Klassen)

2024-01-08 15:47 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Infrastructure/SceneManagement/InitializationLoader.cs
> +			}
Mein Gedanke hier war das man so im Editor die config nicht speichern würde, und eventuell die Möglichkeit hätte separat eine Datei für den Editor anzulegen. Wäre evtl praktisch wenn man das Spiel installiert hat, und diese Settings nicht beim "werkeln" im Editor überschreiben will.

> Wenn LoadAsync nichts findet, dann soll es die Standardwerte setzen. So hat's das bisher auch gemacht (implizit, durch die Zuweisungen der einzelnen Settings in den jeweiligen Kategorie-Klassen)

Hier muss ich nochmal nachhaken:
Meinst du die [Werte](https://github.com/BoundfoxStudios/fairy-tale-defender/blob/e50a9ae653d77882ccca71a125fe34193746e4f9/FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SettingsSystem/ScriptableObjects/SettingsSO.cs#L73)? Darin sah ich halt indirekt das Problem, da so wie ich das verfolgt habe, genau diese verwendet wurden in [SettingsUI](https://github.com/BoundfoxStudios/fairy-tale-defender/blob/e50a9ae653d77882ccca71a125fe34193746e4f9/FairyTaleDefender/Assets/_Game/Scripts/Runtime/UI/Settings/SettingsUI.cs#L82). LoadAsync ist dann bisher sang- und klanglos ausgestiegen und mit den Werten 0 wurde dann auch die Resolution gespeichert in [ApplySettings](https://github.com/BoundfoxStudios/fairy-tale-defender/blob/e50a9ae653d77882ccca71a125fe34193746e4f9/FairyTaleDefender/Assets/_Game/Scripts/Runtime/UI/Settings/SettingsUI.cs#L95C36-L95C36).

2024-01-09 06:58 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Infrastructure/SceneManagement/InitializationLoader.cs
> +			}
> Mein Gedanke hier war das man so im Editor die config nicht speichern würde, und eventuell die Möglichkeit hätte separat eine Datei für den Editor anzulegen.

Dann würd ich lieber im Code einen anderen Pfad für den Editor setzen, also generell. Für alle Files, die wir schreiben. Dann wäre es konsistenter anstatt nur die Settings. :) (Gut, noch schreiben wir nicht mehr).

> Hier muss ich nochmal nachhaken:

Japp, die anderen Werte, außer Screen, werden dort auf den Standard-Wert gesetzt. Daher sollte die SettingsSO-Klasse auch die Werte für Screen per Standard setzen, dann bleibt alles innerhalb dieser Klasse.

2024-01-11 08:19 UTC, M4lph commented
Meintest du so in etwa? Oder lieber die Werte über Konstruktor übergeben?
Oder hab ich es wieder falsch verstanden und du meintest tatsächlich sowas wie 1920x1080 in die Config-Klasse als default für parameterlosen Konstruktor? Da habe ich halt keine Möglichkeit gesehen sinvolle Werte zu setzen - 1920x1080 wäre ja für dich z.B. suboptimal :) Bei anderen Geräten vielleicht sogar gar nicht unterstützt.. Ähnliches Spiel mit der Localization config.

2024-01-11 08:50 UTC, ManuelRauber requested changes
So hätte ich's im Kopf gehabt.

Die Klasse ist ja mutierbar und überschreibt sich quasi selbst, wenn `LoadAsync()` einen Speicherpunkt findet.

Falls sie keinen Speicherpunkt findet, dann wenden wir die Standard-Konfiguration an.

2024-01-11 08:50 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SettingsSystem/ScriptableObjects/SettingsSO.cs
> +		public async UniTask<bool> LoadAsync()
```suggestion
		public async UniTask LoadAsync()
```

2024-01-11 08:50 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SettingsSystem/ScriptableObjects/SettingsSO.cs
> +				return false;
```suggestion
        SetStartConfig();
				return;
```

2024-01-11 08:50 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SettingsSystem/ScriptableObjects/SettingsSO.cs
> +			return true;
```suggestion

```

2024-01-11 08:50 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SettingsSystem/ScriptableObjects/SettingsSO.cs
> +		private void SetStartConfig()
```suggestion
		private void SetDefaultConfiguration()
```

2024-01-11 08:50 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SettingsSystem/ScriptableObjects/SettingsSO.cs
> +		private void SetStartLocale()
```suggestion
		private void SetDefaultLocale()
```

2024-01-11 08:50 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SettingsSystem/ScriptableObjects/SettingsSO.cs
> +		private void SetStartResolution()
```suggestion
		private void SetDefaultResolution()
```

2024-01-11 08:50 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SettingsSystem/ScriptableObjects/SettingsSO.cs
> +			SetStartConfig();
```suggestion

```

2024-01-11 09:23 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SettingsSystem/ScriptableObjects/SettingsSO.cs
> +				return false;
Darüber hatte ich auch nachgedacht, hielt ich aber für einen Nebeneffekt irgendwie, wäre das nicht auch eine potentielle Fehlerquelle in Situation ähnlich [hier](https://github.com/BoundfoxStudios/fairy-tale-defender/blob/e50a9ae653d77882ccca71a125fe34193746e4f9/FairyTaleDefender/Assets/_Game/Scripts/Runtime/UI/Settings/SettingsUI.cs#L100), falls der Save fehlschlägt?
Ansonsten eventuell Naming anpassen, und/oder XML Kommentar dazu, der das erwähnt?

2024-01-11 09:30 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SettingsSystem/ScriptableObjects/SettingsSO.cs
> +				return false;
Hm, eigentlich hast nicht ganz unrecht mit dem Nebeneffekt. 

Mein Gedanke war, wenn nichts geladen werden kann, dass wir dann die Standardwerte nutzen. 
Auf der anderen Seite sind die Standardwerte durch das Erzeugen von `_gameSettings` in OnEnable ja auch gesetzt durch die Zuweisungen in den einzelnen Einstellungsklassen.

Unter dem Aspekt gehört es dann doch in OnEnable rein :) 

Den `UniTask<bool>` brauchen wir dennoch nicht. :)

2024-01-11 10:17 UTC, ManuelRauber approved these changes

2024-01-14 08:20 UTC, merged