feat: save game
BoundfoxStudios/community-project pull request #476
Opened 2024-03-03 09:56 UTC by ManuelRauber

Implementiert eine erste Fassung eines SaveGameManagers nebst einer ersten "Preparation" Szene, die der Spieler sieht, sobald er seinen Spielstand wieder lädt.

2024-03-07 15:21 UTC, M4lph requested changes

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Extensions/StringExtensions.cs
> +
```suggestion
/// <summary>
/// Transforms <paramref name="input"/> to a normalized, comparable representation.
/// </summary>
/// <returns> 
/// A trimmed, lowercase string will be returned, which contains only a-z and 0-9
/// with single hyphens between words as delimiters. Diacritics will be removed.
/// </returns>
```

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Extensions/StringExtensions.cs
> +			return (sb.ToString().Normalize(NormalizationForm.FormC));
```suggestion
			return (sb.ToString().Normalize());
```

Nutzt implizit Form C. https://learn.microsoft.com/en-us/dotnet/api/system.string.normalize?view=net-8.0

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Infrastructure/FileManagement/DirectoryManager.cs
> +
```suggestion
```

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Editor/Menus/FileManagerMenus.cs
> +			var path = Path.Combine(Application.persistentDataPath, Common.Constants.SaveGames.DirectoryName,
Die Funktion wurde im DirectoryManager bereits implementiert, ziemlich ähnlich. Verstoß gegen DRY?
DeleteAll ist bis auf den Pfad, die Bestätigung und die Log Message auch exakt das selbe. Als Variablen rausziehen (Sowas wie DirectoyManager.Delete(path, true, logMessage)? Oder Generalisierung zu früh?

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Infrastructure/FileManagement/DirectoryManager.cs
> +			var result = Directory.EnumerateFiles(CreateDirectoryPath(directory));
Auch hier prüfen ob Pfad existiert?

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SaveGameSystem/SaveGameHash.cs
> +			using var fileStream = new FileStream(saveGameFilePath, FileMode.Open, FileAccess.Read);
Exceptions handeln? FileNotFound, Access etc?

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSO.cs
> +using System.Security.Cryptography;
```suggestion
```

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Sandbox/Kenney.nl - UI Pack RPG/buttonRound_brown.png.meta
Beim Import des Sprite wird Physics Shape generiert. Gewollt?

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Sandbox/Kenney.nl - UI Pack RPG/buttonRound_beige.png.meta
Siehe Button Brown.

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Tests/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSOTests.cs
> +		public IEnumerator LoadSaveGame_CannotLoadWhenFileWasTemperedWith() =>
```suggestion
		public IEnumerator LoadSaveGame_CannotLoadWhenFileWasTamperedWith() =>
```

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Tests/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSOTests.cs
> +				// Temper with the file
```suggestion
				// Tamper with the file
```

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Tests/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSOTests.cs
> +				var meta = await sut.CreateSaveGameAsync("UnitTest", new());
Hier kommt das komplette SaveGame zurück, nicht nur die Meta.
```suggestion
				var saveGame = await sut.CreateSaveGameAsync("UnitTest", new());
```

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Tests/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSOTests.cs
> +				meta.Should().NotBeNull();
```suggestion
				saveGame.Should().NotBeNull();
```

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Tests/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSOTests.cs
> +				saveGame.Data.Should().NotBeNull();
```suggestion
```

Oder entgeht mir hier was? :)

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Tests/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSOTests.cs
> +				LastPlayedDate = DateTime.Now.Subtract(new TimeSpan(1)),
Wohl irrelevant, aber hat 1Tick vor jetzt einen besonderen Grund?

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Tests/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSOTests.cs
> +			}
Invert if/ Guard Clause draus machen?
```suggestion
	if (!Directory.Exists(SaveGamesBackupPath)) return;
	if (Directory.Exists(SaveGamesPath))
	{
		Directory.Delete(SaveGamesPath, true);
	}
	Directory.Move(SaveGamesBackupPath, SaveGamesPath);
```

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/UI/MainMenu/StartContinueButtons.cs
> +				saveGames.SingleOrDefault(saveGame => saveGame.Name == Constants.SaveGames.DefaultSaveGameName) != null);
```suggestion
			ContinueGameButton.gameObject.SetActive(saveGames.Count >= 0);
```

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/UI/MainMenu/StartContinueButtons.cs
> +				// TODO: Needs error handling when save game is null
Wie sollen wir eigentlich mit den TODOS: im Code verfahren? Regelmäßig Editor checken und ab und zu mal aufarbeiten, oder lieber direkt Issues für Triage etc. anlegen?

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/UI/MainMenu/StartContinueButtons.cs
Die Klasse splitten um eher an SRP zu bleiben?

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSO.cs
> +			var slugifiedName = saveName.Slugify();
Slugify nach IsValidSaveGameAsync verschieben?

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSO.cs
> +				var saveGameFile = Path.Combine(meta.Directory, Constants.SaveGames.SaveGameFileName);
Hier kommt ja eigentlich auch nur der Pfad, nicht die Datei an sich zurück.
Dann könnte man sich fragen, wieso in der nächsten Zeile .WriteAsync den Pfad mitgeben, und aus dem return dann neue Variable für den Pfad allokieren? Vllt deswegen in sowas wie FullPath umbenennen um den Unterschied so offensichtlicher zu machen?

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/GameOverUI.cs
>  using TMPro;
```suggestion
```

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/UI/MainMenu/StartContinueButtons.cs
> +			finally
finally ist doch nur sinnvoll wenn in catch ein return oder throw statement ist oder? Oder hast du es hier weil noch kein catch aktuell implementiert ist? Oder bist du einfach sicher dass es so kommen wird? :)

Andererseits wird es ja unabhängig davon aufgerufen ob Exception auftritt oder nicht. Also wieso auch im Fall des Erfolges (Preparation wird geladen, MainMenu wird geschlossen) den Button trotzdem nochmal auf active setzen?

2024-03-07 15:21 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/UI/MainMenu/StartContinueButtons.cs
> +					LastLevel = AllLevelPacks.LevelPacks[0].Levels[0]
Wird nicht richtig gespeichert.
![grafik](https://github.com/BoundfoxStudios/fairy-tale-defender/assets/18291863/bfd4bbcc-6db5-41d2-999f-94d3b709ddde)
Ich vermute die Ursache liegt in IdentifiableSO/ SOIdentity.

2024-03-09 07:21 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSO.cs
> +			var slugifiedName = saveName.Slugify();
Nein, da wir beim Laden und Listing nicht am Namen rumspielen wollen, sondern direkt so, wie erübergeben wurde.

2024-03-09 07:30 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSO.cs
> +				var saveGameFile = Path.Combine(meta.Directory, Constants.SaveGames.SaveGameFileName);
Ob da jetzt `Path` oder `FullPath` steht, weiß ich nicht, ob das groß ein Unterschied macht. Das eine ist eben die Datei und das andere der Pfad, der geschrieben wurde. :)

2024-03-09 07:31 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/UI/MainMenu/StartContinueButtons.cs
Hm, sehe ich nicht hier. "Ins Spiel kommen" ist das, was gewollt wird, mit zwei verschiedenen Buttons. :)

2024-03-09 07:32 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/UI/MainMenu/StartContinueButtons.cs
> +				saveGames.SingleOrDefault(saveGame => saveGame.Name == Constants.SaveGames.DefaultSaveGameName) != null);
In der Theorie können wir ein SaveGame haben, was nicht das Default SaveGame ist. Dann wäre der Button aktiv und würde dann versuchen, ein nicht-existerendes SaveGame zu laden.

2024-03-09 07:35 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/UI/MainMenu/StartContinueButtons.cs
> +					LastLevel = AllLevelPacks.LevelPacks[0].Levels[0]
Das ist korrekt und fixed leider erst mein Nachfolgebranch, da ich das Level_1.asset nochmal neu erstellen musste. Das kann ich im Moment leider nicht cherry-picken :)

2024-03-09 07:36 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/UI/MainMenu/StartContinueButtons.cs
> +				// TODO: Needs error handling when save game is null
Das Todo werd ich noch erledigen mit dem Nachfolgebranch.

Ansonsten steht's im Idealfall gar nicht erst im Code. :) 

Wir mergen ja aktuell nur, damit der Branch hier nicht so riesig wird.

2024-03-09 07:37 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Runtime/UI/MainMenu/StartContinueButtons.cs
> +			finally
Im Endeffekt einfach nur ein "Egal was wo wie passiert, der Button wird wieder aktiv gesetzt".

2024-03-09 07:40 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Tests/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSOTests.cs
> +				LastPlayedDate = DateTime.Now.Subtract(new TimeSpan(1)),
Öhm, nö :-D

2024-03-09 07:41 UTC, ManuelRauber commented on FairyTaleDefender/Assets/_Game/Scripts/Tests/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSOTests.cs
> +				saveGame.Data.Should().NotBeNull();
Weiß nicht, was Du meinst? :)

2024-03-09 08:32 UTC, M4lph approved these changes

2024-03-09 08:32 UTC, M4lph commented on FairyTaleDefender/Assets/_Game/Scripts/Tests/Runtime/Systems/SaveGameSystem/ScriptableObjects/SaveGameManagerSOTests.cs
> +				saveGame.Data.Should().NotBeNull();
Oh, grober Schnitzer von mir, ich hab hier 2x das selbe gelesen °_° Sorry :)

2024-03-11 07:33 UTC, merged