add: LevelSelection Editor Window
BoundfoxStudios/community-project pull request #59
Opened 2022-09-28 07:35 UTC by realTobby

implemented basic level selection window according to https://manuel-rauber.com/2022/03/14/unity-tip-level-selection-editor-window/ - can be found under "Community Project" => "Level Selection"

**Beschreibung**
Beschreibe bitte kurz, was Du in diesem PR machst.
Verlinke auch die Aufgabe, die mit diesem PR einhergeht. 

## Checkliste

- [ ] Aufgabe verlinkt (falls nicht, PR editieren)
- [ ] Tests geschrieben (nur relevant für Code-Änderungen)
- [ ] Dokumentation aktualisiert (nur relevant für System-Entwicklungen)

## PR Typ

- [ ] Bugfix
- [ ] Feature
- [ ] 3D-Modell
- [ ] 2D-Arbeit
- [ ] Sound-Effekte
- [ ] Musik
- [ ] Dokumentation
- [ ] Sonstiges, bitte beschreiben:

2022-09-28 07:57 UTC, realTobby commented
@ManuelRauber Wäre es vielleicht eine gute Idee, die Menüs dynamisch zu erstellen? Dann müssten wir das EditorWindow nicht mehr anpassen später. Knotenpunkt ist der Ordner innerhalb Scenes, die Buttons sind die Scenes im jeweiligen Ordner.
Ist das verständlich? :D (Wir müssen also nur dafür sorgen das die Ordner Struktur immer stimmt)

2022-09-28 07:59 UTC, ManuelRauber commented
> @ManuelRauber Wäre es vielleicht eine gute Idee, die Menüs dynamisch zu erstellen? Dann müssten wir das EditorWindow nicht mehr anpassen später. Knotenpunkt ist der Ordner innerhalb Scenes, die Buttons sind die Scenes im jeweiligen Ordner.
> Ist das verständlich? :D (Wir müssen also nur dafür sorgen das die Ordner Struktur immer stimmt)

Das mit den Menüs machen wir, sobald wir erste Levels/Packs haben. 
Mache ich bei [Bug-A-Ball](https://bugaball.com) auch so, ein paar sind statisch drin und alle Level etc. kommen dynamisch hinzu.

Ich hab beim PrefabManager das ganze mal mit Addressables ausprobiert, das scheint zu funktionieren. Eventuell bauen wir das LevelWindow dann auch auf Addressables um, dann ist's weniger fehleranfällig durch die Ordnerstruktur.

2022-09-28 08:49 UTC, ManuelRauber requested changes
Ein paar Kleinigkeiten zur Korrektur. :)

2022-09-28 08:49 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Constants.cs
> +			public const string LevelSelection = MenuName + "/Level Selection";
Es reicht, wenn wir diese Konstante nur in den Editor-Konstanten definieren, da wir's zur Laufzeit eigentlich hier nicht brauchen. :)

2022-09-28 08:49 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Editor/Menus/LevelSelectionMenu/LevelSelectionEditorWindow.cs
> +		#region Private Fields
Bitte keinerlei `#region` nutzen, siehe [Coding Conventions](https://github.com/BoundfoxStudios/community-project/blob/develop/docs/contributing/technical/coding-conventions.md#kommentare)

2022-09-28 08:49 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Editor/Menus/LevelSelectionMenu/LevelSelectionEditorWindow.cs
> +		private bool _openAdditive;
Hier passt irgendwie die Einrückung nicht.

2022-09-28 08:49 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Editor/Menus/LevelSelectionMenu/LevelSelectionEditorWindow.cs
> +using BoundfoxStudios.CommunityProject.SceneManagement;
Diese Datei liegt generell im falschen Ordner.

Aktuell liegt sie unter `Editor/Menus/LevelSelectionMenu`.

Da es aber ein Window ist, sollte es eher unter `Editor/Windows` liegen. Eigenen weiteren Ordner braucht's dort drin dann nicht, besteht ja aktuell aus einer Datei.

2022-09-28 08:49 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Editor/Menus/LevelSelectionMenu/LevelSelectionEditorWindow.cs
> +		private void RenderGameplay()
Kann aktuell noch entfernt werden, macht ja nichts sinnvolles.

2022-09-28 08:49 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Editor/Menus/LevelSelectionMenu/LevelSelectionEditorWindow.cs
> +			EndFoldoutGroup("Managers", showManagers);
Den Part könnte man in eine eigene Methode auslagern und dann bei `RenderScenes` aufrufen.

Dann könnte man jeweils auch die `show*`-Variablen wieder auf ein `show` umbenennen.

2022-09-28 12:02 UTC, ManuelRauber requested changes
Eine letzte kleine Änderung :)

2022-09-28 12:02 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Editor/Windows/LevelSelectionEditorWindow.cs
> +namespace BoundfoxStudios.CommunityProject.Editor.Windows.LevelSelectionEditorWindow
```suggestion
namespace BoundfoxStudios.CommunityProject.Editor.Windows
```

Namespaces sind nur auf Ordner-Ebene, d.h. es endet hier beim Ordner "Windows" :)

2022-09-28 16:23 UTC, merged

2022-09-28 16:23 UTC, ManuelRauber commented
Herzlichen Dank! :)

2022-10-18 07:52 UTC, ManuelRauber commented
@all-contributors please add @realTobby for code

2022-10-18 08:17 UTC, ManuelRauber commented
@all-contributors please add @realTobby for code