add: InputReaderSO
BoundfoxStudios/community-project pull request #71
Opened 2022-09-29 07:14 UTC by Salja

Basic implementaion of basic "InputReaderSO" according to https://github.com/BoundfoxStudios/community-project/issues/69

Signed-off-by: Christian Schamara <schamara.christian@gmail.com>

**Beschreibung**
Basis Implementierung vom InputReaderSO https://github.com/BoundfoxStudios/community-project/issues/69
Dies ist nur die Basis Implementierung des "InputReaders" und enthält noch keinerlei weiteren Funktionen.
Die Idee ist den "InputReader" als dynamisches ScriptableObject immer dann zu referenzieren wenn an einer Stelle ein Input benötigt wird, durch delegates kann dann an dieser Stelle auf ein bestimmtes Input Event gehört werden, um es dann weiter zu verarbeiten. 

## Checkliste

- [ ] Aufgabe verlinkt (falls nicht, PR editieren)
- [ ] Tests geschrieben (nur relevant für Code-Änderungen)
- [ ] Dokumentation aktualisiert (nur relevant für System-Entwicklungen)

## PR Typ

- [ ] Bugfix
- [ ] Feature
- [ ] 3D-Modell
- [ ] 2D-Arbeit
- [ ] Sound-Effekte
- [ ] Musik
- [ ] Dokumentation
- [ ] Sonstiges, bitte beschreiben:

2022-09-29 07:20 UTC, Salja commented
@ManuelRauber ich habe bewusst auf die ActionMap "Camera" verzichtet, ich sehe keine wirkliche Notwendigkeit wieso die Camera ein extra ActionMap haben sollte, daher denke ich sollte die "Gameplay Camera" unter die ActionMap (Gameplay) kommen als CameraMovement (Action).

2022-09-29 07:27 UTC, Salja commented
Note: Da ich hier die Generate C# Klasse vom neuen InputSystem verwende haben wir nicht mehr die Möglichkeit auf ein bestimmtes ControlScheme zu reagieren, partisch gesagt haben wir keinen "access" mehr um zu sehen welches "ControlScheme" grade aktive ist, um das ganze zu umgehen müssen wir zum gegeben Zeitpunkt ein UserInputHandler erstellen welcher einen neuen "InputUser" erstellt und diesen bei default ein ControlScheme z.B "Keyboard / Mouse" den User zuweißt.

Unity hat an dieser Stelle leider noch etwas nachzuholen und ich hoffe das Sie in Zukunft eine einfachere Möglichkeit bieten um mit der C# Class das CurrentControlScheme einzusehen.

Siehe dazu auch meinen Unity Forum Beitrag https://forum.unity.com/threads/generated-c-class-current-control-scheme.1314786/#post-8320842

2022-10-03 09:28 UTC, ManuelRauber commented
> @ManuelRauber ich habe bewusst auf die ActionMap "Camera" verzichtet, ich sehe keine wirkliche Notwendigkeit wieso die Camera ein extra ActionMap haben sollte, daher denke ich sollte die "Gameplay Camera" unter die ActionMap (Gameplay) kommen als CameraMovement (Action).

Guter Hinweis! Können wir ja dann auch entsprechend ein/ausschalten je nach Optionen. 

> Note: Da ich hier die Generate C# Klasse vom neuen InputSystem verwende haben wir nicht mehr die Möglichkeit auf ein bestimmtes ControlScheme zu reagieren [...]

Ich denke, dass wir das vorerst auch nicht brauchen und erstmal nur ganz normal mit Keyboard + Maus loslaufen. Wenn da ganze dann konkreter wird, kann man das Control-Schema-Handling noch einbauen. :)

2022-10-03 09:36 UTC, ManuelRauber requested changes
Eine kleine Änderung noch, siehe Kommentar im Code :)

2022-10-03 09:36 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Input/InputReaderSO.cs
> +	public class InputReaderSO : ScriptableObject, GameInput.IGameplayActions, GameInput.IUIActions
SO bitte noch in einen weiteren Unterordner "ScriptableObjects" verschieben, namespace wird dann entsprechend auch `BoundfoxStudios.CommunityProject.Input.ScriptableObjects`. Siehe auch die anderen SO's, die bereits im Projekt sind.

2022-10-05 17:56 UTC, ManuelRauber approved these changes
Herzlichen Dank! :)

2022-10-05 19:01 UTC, merged

2022-10-18 07:52 UTC, ManuelRauber commented
@all-contributors please add @Salja for code

2022-10-18 08:16 UTC, ManuelRauber commented
@all-contributors please add @Salja for code