Add MainAudioMixer
BoundfoxStudios/community-project pull request #82
Opened 2022-10-08 13:37 UTC by BlackJack237

#60 Added MainAudioMixer

**Beschreibung**
AudioMixer für das Game geaddet, Volumes der einzelnen Channels(groups) verfügbar gemacht.

## Checkliste

- [ ] Aufgabe verlinkt (falls nicht, PR editieren)
- [ ] Tests geschrieben (nur relevant für Code-Änderungen)
- [ ] Dokumentation aktualisiert (nur relevant für System-Entwicklungen)

## PR Typ

- [ ] Bugfix
- [ ] Feature
- [ ] 3D-Modell
- [ ] 2D-Arbeit
- [ ] Sound-Effekte
- [ ] Musik
- [ ] Dokumentation
- [ ] Sonstiges, bitte beschreiben:

2022-10-08 19:03 UTC, ManuelRauber requested changes
Danke für den PR. 

Zwei Dinge würde ich gerne noch ändern: 

1) Kannst Du bitte den MainAudioMixer nach `Settings/Audio` verschieben?
2) In Deinem Branch ist noch ein Merge-Commit drin, den ich nicht möchte. Kannst Du diesen entfernen? Falls Du nicht weiß, wie das geht, kann ich das gerne selbst machen, dazu müsstest Du dieser kleinen Anleitung folgen: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests

Danke! :)

2022-10-09 07:02 UTC, BlackJack237 commented
Wenn ich richtig bin sollte es so passen. Wenn nicht bitte melden.

2022-10-09 07:23 UTC, BlackJack237 commented
Sorry wollte den nicht schließen. Soll ich einen neuen machen?

2022-10-09 07:55 UTC, ManuelRauber commented
> Sorry wollte den nicht schließen. Soll ich einen neuen machen?

Ich konnte ihn wieder aufmachen :)

2022-10-09 08:10 UTC, merged

2022-10-18 07:51 UTC, ManuelRauber commented
@all-contributors please add @BlackJack237 for code

2022-10-18 08:10 UTC, ManuelRauber commented
@all-contributors please add @BlackJack237 for code

2022-10-18 08:11 UTC, ManuelRauber commented
@all-contributors please add @BlackJack237 for code

2022-10-18 08:13 UTC, ManuelRauber commented
@all-contributors please add @BlackJack237 for code