Issue #61: Added a basic BackgroundMusicPlayer
BoundfoxStudios/community-project pull request #84
Opened 2022-10-11 08:50 UTC by M4lph

Added a basic BackgroundMusicPlayer, also added ScriptableObjects for playlists and AudioClips. Moved AudioMixer to _Game/Settings/Audio for Issue #61 

**Beschreibung**
Beschreibe bitte kurz, was Du in diesem PR machst.
Verlinke auch die Aufgabe, die mit diesem PR einhergeht. 

## Checkliste

- [x] Aufgabe verlinkt (falls nicht, PR editieren)
- [ ] Tests geschrieben (nur relevant für Code-Änderungen)
- [ ] Dokumentation aktualisiert (nur relevant für System-Entwicklungen)

## PR Typ

- [ ] Bugfix
- [x] Feature
- [ ] 3D-Modell
- [ ] 2D-Arbeit
- [ ] Sound-Effekte
- [ ] Musik
- [ ] Dokumentation
- [ ] Sonstiges, bitte beschreiben: 

-- edit by Manu

fixes #61

2022-10-11 12:34 UTC, ManuelRauber requested changes

2022-10-11 12:34 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scenes/Managers/PersistentManagers.unity
> +  m_PlayOnAwake: 1
Auch wenn's hier absolut egal ist, aber Ordnung muss sein: Könntest Du bei der AudioSource im PersistentManager noch "Play On Awake" ausschalten?

2022-10-11 12:34 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/BackgroundMusicPlayer.cs
> +	[RequireComponent(typeof(AudioSource))]
Hier fehlt mir noch ein `AddComponentMenu`, siehe z.B. [hier](https://github.com/BoundfoxStudios/community-project/blob/develop/CommunityProject/Assets/_Game/Scripts/Runtime/SceneManagement/SceneLoader.cs#L9)

2022-10-11 12:34 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/BackgroundMusicPlayer.cs
> +		private PlaylistSO playlist;
Der Vollständigkeit halber: 

```suggestion
		private PlaylistSO Playlist;
```

2022-10-11 12:34 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/BackgroundMusicPlayer.cs
> +#endif
Gerne hier das `if UNITY_EDITOR` wegmachen und direkt `Debug.LogWarning` (vielleicht sogar Error?) nutzen.

Hintergrund ist, dass wir sicherlich irgendwann mal (famous last words) auf eine eigene Logging-Klasse umbauen und solche Dinge wie `#if UNITY_EDITOR` zentral regeln, sonst ziehen sich solche Direktiven immer hässlich durch die Codebase.

2022-10-11 12:34 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/BackgroundMusicPlayer.cs
> +			while (true)
Ich bin kein Freund von `while (true)`, daher würde hier gerne zwei Alternativen vorschlagen:

## Alternative 1: Application.quitting
Du kannst ein Feld `_isQuitting` anlegen und via [Applikation.quitting](https://docs.unity3d.com/ScriptReference/Application-quitting.html) mitbekommen, wann der Player geschlossen wird. Allerdings müsste man auch noch auf eine Playmode-Änderung im Editor reagieren können.

Dann würde man die Bedingung ändern auf ein `while (!_isQuitting)` und hat eine echte Austiegsbedingung.

## Alternative 2: "Rekursion"
Anstelle des Loops könnte `PlayMusicAsync` sich selbst aufrufen.
Dazu müsste man folgendes machen:

* Die `Awake`-Methode wird wieder ganz normal `private void Awake`
* Die Signatur von `PlayMusicAsync` ändert sich auf `private async UniTaskVoid PlayMusicAsync()`
* `Awake` ruft die Methode dann via `PlayMusicAsync().Forget()` auf
* Der rekursive Aufruf innerhalb von `PlayMusicAsync` wäre dann auch via `PlayMusicAsync().Forget()`

Hintergrund ist, dass wir hier beim rekursiven Aufrufen nicht `await` nutzen dürfen, da wir sonst (wahrscheinlich wird's nie dazu kommen, aber man weiß ja nie) irgendwann einen StackOverflow bekommen, da wir rekursiv immer weiter eintauchen und nie fertig werden. Durch das `.Forget()`, was von UniTask bereit gestellt wird, durchbrechen wir rekursive absteigen.

2022-10-11 12:34 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/BackgroundMusicPlayer.cs
> +				if (clip)
Ggf. könnte man hier noch ein Warning ausgeben?

Und falls der Umbau dieser Methode in Richtung Alternative 2 geht, könnte man die Bedingung auch umdrehen und ein `if (!clip) { Warning; return;` draus machen. -> Weniger Einrücktiefe für den Code, der wirklich was tut. :)

2022-10-11 12:34 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/ScriptableObjects/PlaylistItemSO.cs
> +		public string Url => url;
Wie im Discord, hier nochmal der Vollständigkeithalber:

```suggestion
		public AudioClip AudioClip;
		public string Title;
		public string Interpreter;
		public string Url;
```

Streng genommen ist die Aufteilung natürlich sinnvoller, da man nur eine ReadOnly-API nach draußen anbietet, auf der anderen Seite wird ja auch das private Feld durch `SerializeField` quasi "öffentlich" und damit wieder beschreibbar. :)

2022-10-11 12:34 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/ScriptableObjects/PlaylistItemSO.cs
> +namespace BoundfoxStudios.CommunityProject.Audio
```suggestion
namespace BoundfoxStudios.CommunityProject.Audio.ScriptableObjects
```

2022-10-11 12:34 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/ScriptableObjects/PlaylistSO.cs
> +namespace BoundfoxStudios.CommunityProject.Audio
```suggestion
namespace BoundfoxStudios.CommunityProject.Audio.ScriptableObjects
```

2022-10-11 12:34 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/ScriptableObjects/PlaylistSO.cs
> +		private PlaylistItemSO[] clips;
```suggestion
		private PlaylistItemSO[] Clips;
```

2022-10-11 12:34 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/ScriptableObjects/PlaylistSO.cs
> +			} while (_nextClipIndex == _lastClipIndex);
Hier haben wir zwei fiese Bugs drin:

## Bug 1: Keine Items in der Liste
Sollten sich keinerlei Clips in der Liste befindet -> Endlosschleife.
Würde bei 0 Items in der Liste knallhart eine Exception werfen, weil das ein Implementierungsfehler ist.

## Bug 2: Nur ein Item in der Liste
Sollte sich nur ein Clip in der Liste befinden -> Endlosschleife.
Einfach direkt das eine Item zurückgeben.

_Höhö streng genommen könnte man auch eine Exception werfen, wenn weniger als 2 Items in der Liste sind, da die Methode ja ihre Bedingung sonst er füllen könnte :D_

2022-10-11 12:34 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/ScriptableObjects/PlaylistSO.cs
> +			return clips[_nextClipIndex].AudioClip;
Hier überlege, ob man nicht nochmal prüft, das AudioClip auch gesetzt ist (man könnte ja ein Item angelegt haben, aber vergessen den Clip reinzulegen).

Auf der andere Seite könnte das auch was sein, was wir später generell validieren. Hm. 🤔

2022-10-11 12:34 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/ScriptableObjects/PlaylistSO.cs
> +		/// <returns>Another <see cref="AudioClip"/> than the one previously played in this playlist</returns>
Ich werd gleich noch eine Änderung an den Coding Conventions vornehmen:

> Beschreibe jede öffentliche Klasse, Methode und Eigenschaft welchen Zweck sie erfüllt, z.B.

Das wird sich ändern in ein "Wo es Sinn macht". Weil hier ist der Methodenname aussagekräftig, dass das Kommentar wahrlich redundant ist.

2022-10-11 12:39 UTC, M4lph commented on CommunityProject/Assets/_Game/Scenes/Managers/PersistentManagers.unity
> +  m_PlayOnAwake: 1
Klar, werde ich machen, nicht gemerkt :)
Wie siehts mit anderen Optionen im Editor aus wie z.B. Tags? Derzeit eigtl kein passendes, könnte evtl aber irgendwann Sinn machen.
Static bzw die Unteroptionen haben in dem Fall ja glaube ich keine wirkliche Auswirkung, lasse mich aber auch hier gern eines besseren belehren :)

2022-10-11 12:41 UTC, M4lph commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/BackgroundMusicPlayer.cs
> +#endif
Super, das wollte ich eigtl auch noch Fragen, wie es mit eigenem Logger aussieht 👍

2022-10-11 12:43 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scenes/Managers/PersistentManagers.unity
> +  m_PlayOnAwake: 1
Guter Hinweis.

Tags sehe ich hier keine. 
Static mach ich generell alles, was ich static machen kann. Ob das wirklich was bringt, gerade bei den leeren GO in der PersistentScene, weiß ich allerdings auch nicht. Schaden tut's aber nicht :D

2022-10-11 12:51 UTC, M4lph commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/ScriptableObjects/PlaylistSO.cs
> +			} while (_nextClipIndex == _lastClipIndex);
Auch die waren mir durchaus bewusst.
Aber mit einer Playlist erstmal dachte ich könnte man sich den Fast Exit aus der Methode sparen undso, weil wahrscheinlich mehr als 2 Items.
Aber werde ich ändern, bin dann aber wohl auch eher für den schnellen Ausstieg mit ner if Abfrage statt Exception zu werfen.

2022-10-11 13:07 UTC, M4lph commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/BackgroundMusicPlayer.cs
> +			while (true)
Welche Alternative wäre dir denn lieber/ welche ist "besser"?
Ich kann ich die Vor- und Nachteile nicht wirklich einschätzen und abwägen.
Die 2. Alternative hört sich für mich nach etwas mehr Overhead wie die andere an, aber wie gesagt, keine Ahnung :)

2022-10-11 13:12 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Audio/BackgroundMusicPlayer.cs
> +			while (true)
Hm, ich glaube, hätte ich den Task gemacht, hätte ich Variante 2 implementiert. So ist's zumindest auch bei Bug-A-Ball drin und hat bisher keine Probleme beschert. :)

Ist von der Implementierung tatsächlich nachher weniger als jetzt und weniger als Variante 1 :D

2022-10-12 08:48 UTC, ManuelRauber approved these changes

2022-10-12 19:54 UTC, ManuelRauber approved these changes
Tiptop :)

2022-10-12 19:54 UTC, ManuelRauber commented
fixes #61

2022-10-12 20:32 UTC, merged

2022-10-18 08:09 UTC, ManuelRauber commented
@all-contributors please add @M4lph for code, doc