Feature/scene for credits
BoundfoxStudios/community-project pull request #90
Opened 2022-10-13 14:11 UTC by ThKattanek

**Beschreibung**
Credit Screen habe ich hier hinzugefügt. Und sollte auch soweit laufen. Benötige aber noch ein Tip wie ich wieder zurück zum Hauptmenü komme, Button dafür ist schon mal platziert :) 
https://github.com/BoundfoxStudios/community-project/issues/50

## Checkliste

- [ ] Aufgabe verlinkt (falls nicht, PR editieren)
- [ ] Tests geschrieben (nur relevant für Code-Änderungen)
- [ ] Dokumentation aktualisiert (nur relevant für System-Entwicklungen)

## PR Typ

- [ ] Bugfix
- [ ] Feature
- [ ] 3D-Modell
- [ ] 2D-Arbeit
- [ ] Sound-Effekte
- [ ] Musik
- [ ] Dokumentation
- [ ] Sonstiges, bitte beschreiben:

2022-10-13 14:49 UTC, ManuelRauber commented
Ui, bevor ich mir den anschaue, müssen bitte alle Merge-Commits entfernt werden aus der History :)
Falls ich hier unterstützen soll, brauch ich Schreibrechte auf den PR (siehe https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests)

2022-10-13 15:14 UTC, ThKattanek commented
Du solltest die Rechte haben. Ich denke du bist schneller darin das zu bereinigen. Ok für mich also in Zukunft keine merges mehr im branch :)
![grafik](https://user-images.githubusercontent.com/14269404/195635806-2fecf7a4-006f-4ee8-a8af-cd9fab18f4ee.png)

2022-10-13 15:18 UTC, ManuelRauber commented
> Du solltest die Rechte haben. Ich denke du bist schneller darin das zu bereinigen. Ok für mich also in Zukunft keine merges mehr im branch :)
> ![grafik](https://user-images.githubusercontent.com/14269404/195635806-2fecf7a4-006f-4ee8-a8af-cd9fab18f4ee.png)

Du kannst schon "mergen", allerdings als Rebase, das unterstützen die meisten Git-UI-Tools in der Regel auch. Musst bei Deinem mal schauen. :)

Hab's eben rebased und bei Dir gepusht. Code schau ich mir später an :)

2022-10-13 15:24 UTC, ThKattanek commented
Super danke. :+1:

2022-10-14 06:48 UTC, ManuelRauber requested changes
Hey @ThKattanek 

Das ist eine sehr, sagen wir mal, kreative Lösung :) 

Zwei große seh ich aktuell:

1. Sie ist viel zu komplex :) (mehr dazu weiter unten)
2. Unity spuckt beim Start einige Warnungen aus, was natürlich sehr uncool ist:
![image](https://user-images.githubusercontent.com/740791/195777997-2c21cd15-9433-4fd6-a9c4-68d63941e50f.png)

### Warum zu komplex?

_Der Teil ist auch etwas mir geschuldet, da ich das Issue hätte genauer beschreiben können_

Du hast ein Verhalten von einer ScrollView nachimplementiert, die das alles schon kann. :)
Prinzipiell bräuchtest Du folgendes:

* Eine ScrollView (deren Scrollbars Du dann einfach löschst)
* Im Content der ScrollView eine VerticalLayoutGroup und auf dem Content selbst ein ContentSizeFitter dessen Vertical auf "Preferred Size" gestellt ist
* In der VerticalLayoutGroup genau ein TMP-Objekt

Im TMP-Objekt kannst Du statische Texte bereits vordefiniert reinmachen und weitere Dinge als Platzhalter definieren, in dem Du z.B. einfach `{{MusicCredits}}` reinschreibst in den Text.

Im Skript kann man dann im Awake die weiteren Credits zusammenbauen und mit einem simplen Replace arbeiten, um den Platzhalter `{{MusicCredits}}` zu ersetzen.

Zum Scrollen der Credits kann man auf der ScrollView die Eigenschaft `verticalNormalizedPosition` nutzen und diese wieder zurücksetzen, wenn man am Ende angekommen ist.

Alles in allem braucht's eventuell ~25 Zeilen Code 🙈

2022-10-14 06:48 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/UI/CreditText.cs
> +				Process.Start(Url);
`Application.OpenURL` wäre hier deutlich schöner als ein `Process.Start`.

Generell müsstest Du, wenn Du die Credits nach meiner Vorschlag umbaust, dies auch anderes lösen, hier gibt's ein kleines Tutorial, wie: https://deltadreamgames.com/unity-tmp-hyperlinks/
Am besten als eigene kleine Komponente, dann kann man die wunderbar für andere Links im Projekt wiederverwenden. :)

2022-10-14 08:06 UTC, ThKattanek commented
> 2\. Unity spuckt beim Start einige Warnungen aus, was natürlich sehr uncool ist:
>         ![image](https://user-images.githubusercontent.com/740791/195777997-2c21cd15-9433-4fd6-a9c4-68d63941e50f.png)
> 
> 
> ###

Bei mir kommt da keine Warnungen. Arbeite unter Linux. Sehr Merkwürdig.

2022-10-14 08:08 UTC, ManuelRauber commented
> > 2. Unity spuckt beim Start einige Warnungen aus, was natürlich sehr uncool ist:
> > ![image](https://user-images.githubusercontent.com/740791/195777997-2c21cd15-9433-4fd6-a9c4-68d63941e50f.png)
> 
> Bei mir kommt da keine Warnungen. Arbeite unter Linux. Sehr Merkwürdig.

Hast Du eventuell in der Konsole Warnings ausgeblendet? Die Warnungen müssen kommen bei Dir, weil Du MonoBehaviour hier falsch nutzt durch das `new`

2022-10-14 08:11 UTC, ThKattanek commented
> 1. Sie ist viel zu komplex :) (mehr dazu weiter unten)

Willst du mir damit sagen das die ganze Arbeit umsonst war. Meine Lösung ist dafür aber viel Flexibler. Wollte eigtl. noch das ganze auf hübschen. z.B. Beim drüberfahen mit der Maus über ein Link das sich die Farbe ändert oder eine kleine Animation die die Zeile bissl nach links und rechts schwabbeln lääst. Ja ich denke immer sehr LowLevel liegt wohl an meiner C/C++ Erfahrungen. C# und Unity ist neu für mich.

2022-10-14 08:39 UTC, ManuelRauber commented
> Willst du mir damit sagen das die ganze Arbeit umsonst war.

Ein Lernfaktor ist immer gegeben. :)

>  Beim drüberfahen mit der Maus über ein Link das sich die Farbe ändert oder eine kleine Animation die die Zeile bissl nach links und rechts schwabbeln lääst.

Ist aktuell nicht Bestandteil vom Task, lässt sich aber alles auf einem TMP-Objekt problemlos machen. Wenn Du mal in einem neuen Projekt TMP importierst und zusätzlich die Examples (https://docs.unity3d.com/Packages/com.unity.textmeshpro@3.2/manual/index.html#importing-examples-and-additional-resources), findet man super viele Beispiele, was TMP alles so kann. Grafiken einbinden, Hover-Interkation mit Links, Animation von Text etc. :)

2022-10-14 08:44 UTC, ThKattanek commented
> Ein Lernfaktor ist immer gegeben. :)

Das stimmt wohl, aber meine Freizeit ist auch begrenzt. :) Wenn das ganze noch Zeit hat werde ich mir das alles nochmal ansehen.

2022-10-14 08:46 UTC, ManuelRauber commented
> > Ein Lernfaktor ist immer gegeben. :)
> 
> Das stimmt wohl, aber meine Freizeit ist auch begrenzt. :) Wenn das ganze noch Zeit hat werde ich mir das alles nochmal ansehen.

Es läuft nichts weg :) Und das mit der Freizeit ist mir bewusst, dennoch muss ich von vornherein auf Sauberkeit achten, sonst fällt uns das irgendwann auf die Füße. Gut, bei den Credits jetzt natürlich nicht, dennoch ist's schön, wenn die Codebase generell sauber und aufgeräumt ist.

Alternativ kann man bei Tasks natürlich auch generell erstmal reinschreiben, wie man es implementiert und dann kann ich schon Feedback geben, bevor es umgesetzt wird 👍

2022-10-14 08:48 UTC, ThKattanek commented
Auf jeden Fall sollten die Task dann in Zukunft auch so formuliert sein, das es das ganze weiter einschränkt. Gebe 10 Entwickler eine Aufgabe jeder hat ne andere Lösung aber das was rauskommt ist gleich.

2022-10-14 08:48 UTC, ThKattanek commented
> Alternativ kann man bei Tasks natürlich auch generell erstmal reinschreiben, wie man es implementiert und dann kann ich schon Feedback geben, bevor es umgesetzt wird 👍

Ja das werde ich in Zunkunft machen :)

2022-11-08 12:05 UTC, closed without merging