Json File Manager implementiert
BoundfoxStudios/community-project pull request #92
Opened 2022-10-15 17:36 UTC by fastFox2

**Beschreibung**
Implementierung eines Json File Managers zum laden und speichern von Serialisierbaren Objekten nach Json. Vorhandensein von Dateien kann überprüft werden.

https://github.com/BoundfoxStudios/community-project/issues/67

## Checkliste

- [ ] Aufgabe verlinkt (falls nicht, PR editieren)
- [ ] Tests geschrieben (nur relevant für Code-Änderungen)
- [ ] Dokumentation aktualisiert (nur relevant für System-Entwicklungen)

## PR Typ

- [ ] Bugfix
- [ ] Feature
- [ ] 3D-Modell
- [ ] 2D-Arbeit
- [ ] Sound-Effekte
- [ ] Musik
- [ ] Dokumentation
- [ ] Sonstiges, bitte beschreiben:

2022-10-15 21:33 UTC, ManuelRauber requested changes
Schöner PR! Ein paar Kleinigkeiten hab ich allerdings noch.

Gute Wahl der Scriptplatzierung 👍

2022-10-15 21:33 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Infrastructure/FileManager/JsonFileManager.cs
> +		}
Das musst Du in ein eigenes Skript auslagern und in der Editor-Assembly ablegen (`Scripts/Editor/Menus` am besten).

Hintergrund ist, dass der Namespace `UnityEditor` nicht beim Build zur Verfügung steht (ich lass gleich mal hier auf GitHub ein Build los, dann wirst es sehen) und daher nicht gebaut werden kann. :)

2022-10-15 21:33 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Infrastructure/FileManager/JsonFileManager.cs
> +
Eine Leerzeile zu viel

2022-10-15 21:33 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Infrastructure/FileManager/JsonFileManager.cs
> +			var jsonSerialization = JsonUtility.ToJson(serializable);
Fast gut! :)

Problem ist, falls im Key Order angegeben sind, dann wird `File.WriteAllText` einen Fehler werfen, da es den Ordner nicht gibt. Am besten machst du noch eine weitere Methode `EnsurePath(string path)`, die den `filePath` bekommt und via `Directory.Exists` prüfen kann, ob ein Ordner existiert und falls nicht via `Directory.CreateDirectory` diesen anlegt.

2022-10-15 21:33 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Infrastructure/FileManager/JsonFileManager.cs
> +			var filePath = Path.Combine(_rootPath, key);
Das Zusammenbauen vom Key machst Du an mehreren Stellen. Könnte man noch in eine kleine Methode auslagern und nutzen :)

2022-10-15 21:33 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Infrastructure/FileManager/JsonFileManager.cs
> +
Eine Leerzeile zu viel

2022-10-15 21:33 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Infrastructure/FileManager/JsonFileManager.cs
> +using UnityEditor;
Der Namespace muss raus, siehe Kommentar bei `OpenApplicationData`

2022-10-15 21:33 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Infrastructure/FileManager/JsonFileManager.cs
> +namespace BoundfoxStudios.CommunityProject.Infrastructure.FileManager
Namespace `FileManager` ist fast gut, würde ich hier auf `FileManagement` ändern (und entsprechend auch der Ordner dann).

2022-10-15 21:57 UTC, fastFox2 commented on CommunityProject/Assets/_Game/Scripts/Runtime/Infrastructure/FileManager/JsonFileManager.cs
> +			var jsonSerialization = JsonUtility.ToJson(serializable);
Kann bei dem Pfad den `Directory.Exists` bekommt auch schon der Dateiname dabei sein? Wahrscheinlich nicht, oder?

2022-10-15 22:14 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Infrastructure/FileManager/JsonFileManager.cs
> +			var jsonSerialization = JsonUtility.ToJson(serializable);
> Kann bei dem Pfad den `Directory.Exists` bekommt auch schon der Dateiname dabei sein? Wahrscheinlich nicht, oder?

Du kannst an den Pfad via `Path.GetDirectoryName` dran kommen. :)

2022-10-16 08:15 UTC, ManuelRauber requested changes
Fast geschafft :)

2022-10-16 08:15 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Editor/Menus/JsonFileManagerMenu.cs
> +		[MenuItem("Community Project/Open Application Data")]
```suggestion
		[MenuItem(Constants.MenuNames.MenuName + "/Open Application Data")]
```

sowie

2022-10-16 08:15 UTC, ManuelRauber commented on CommunityProject/Assets/_Game/Scripts/Runtime/Infrastructure/FileManagement/JsonFileManager.cs
> +			EnsurePath(path);
Ich mag die Platzierung von EnsurePath hier nicht, da `CreateFilePath` auch bei `ReadAsync` aufgerufen wird. D.h. wenn man nur versuchen würde, Dinge zu lesen, aber noch nicht zu speichern, dann würde man im Zweifel leere Ordner erstellen.

Wenn Du das das `EnsurePath` nur nach `WriteAsync` packst, wäre das super :)

2022-10-16 08:33 UTC, ManuelRauber approved these changes
Herzlichen Dank! :)

2022-10-16 08:33 UTC, merged

2022-10-18 07:50 UTC, ManuelRauber commented
@all-contributors please add @M4lph for code, doc

2022-10-18 07:51 UTC, ManuelRauber commented
@all-contributors please add @fastFox2 for code

2022-10-18 08:09 UTC, ManuelRauber commented
@all-contributors please add @fastFox2 for code